// Tests: 12 §7.10 export golden outputs (LF, now = 2026-09-29 14:05), the empty-state rows, the default file name,
//        Q-3 (Selected Questions = the multi-selection), §4.5 (UTF-8 without BOM).
import Foundation
import Testing
@testable import AACore

enum SireExportFixture {
    static let zone = TimeZone(identifier: "Europe/Athens")!
    static let now: Date = {
        var c = DateComponents(); c.year = 2026; c.month = 9; c.day = 29; c.hour = 14; c.minute = 5
        var cal = Calendar(identifier: .gregorian); cal.timeZone = zone
        return cal.date(from: c)!
    }()
    static func at(_ h: Int, _ m: Int) -> NetDateTime { NetDateTime(year: 2026, month: 9, day: 30, hour: h, minute: m, kind: .local) }
    static let session = SireSessionSnapshot(
        statuses: [("2.1.10", "Checked"), ("1.1.1", "InProgress")], bookmarks: ["2.1.2"], forExport: ["2.1.10"],
        tasks: [.init(questionNumber: "2.1.10", text: "Check log", isCompleted: true, createdAt: at(10, 0)),
                .init(questionNumber: "2.1.2", text: "Sight cert", isCompleted: false, createdAt: at(9, 0)),
                .init(questionNumber: "2.1.10", text: "Review plan", isCompleted: false, createdAt: at(9, 30))])
    static let filtered = [SireSynthetic.q2110, SireSynthetic.q111]

    static func build(_ mode: String, session: SireSessionSnapshot = session, identified: SireIdentifiedTasks = SireSynthetic.identified,
                      selected: Set<String> = []) -> String {
        SireExport.build(mode: mode, all: SireSynthetic.questions, session: session, identified: identified,
                         filtered: filtered, selected: selected, now: now, zone: zone)
    }

    /// The body between the header frame (5 lines) and the footer frame (blank + 3 lines).
    static func body(_ mode: String, session: SireSessionSnapshot = session, identified: SireIdentifiedTasks = SireSynthetic.identified,
                     selected: Set<String> = []) -> String {
        let text = build(mode, session: session, identified: identified, selected: selected)
        var lines = text.components(separatedBy: "\n")
        #expect(lines.last == "")
        lines.removeLast()
        let inner = lines[5..<(lines.count - 4)]
        return inner.joined(separator: "\n") + "\n"
    }
}

@Suite struct SireExportTests {
    typealias F = SireExportFixture

    @Test func modeListAndDefault() {
        #expect(SireExport.modes == ["All Tasks", "Completed Tasks", "Pending Tasks", "Questions with Tasks",
                                     "Selected Questions", "For Export Tagged", "Bookmarked Questions", "Current Filter Results",
                                     "By Chapter", "By ROVIQ Location", "By Status", "By Vessel Type",
                                     "Print Checklist", "Inspection Summary", "Full Session Report", "Identified Tasks"])
        #expect(SireExport.defaultMode == "Print Checklist")
    }

    // TV: 12 §7.10 Print Checklist (whole file)
    @Test func printChecklist() {
        #expect(F.build("Print Checklist") == """
        ============================================================
          SIRE 2.0 Knowledge Bank Export — Print Checklist
          Generated: 2026-09-29 14:05
        ============================================================

          INSPECTION CHECKLIST
          Total questions: 3

        [~] Q 1.1.1 — \("")
        [ ] Q 2.1.2 — Alpha check
              [ ] Sight cert
        [x] Q 2.1.10 — Beta check
              [x] Check log
              [ ] Review plan

        ============================================================
          Generated by AA — SIRE 2.0 Knowledge Bank
        ============================================================

        """)
    }

    // TV: 12 §7.10 All Tasks
    @Test func allTasks() {
        #expect(F.body("All Tasks") == "Q 2.1.2 — Alpha check\n  [ ] Sight cert\n\nQ 2.1.10 — Beta check\n  [ ] Review plan\n  [x] Check log\n\n")
    }

    // TV: 12 §7.10 Full Session Report
    @Test func fullSessionReport() {
        #expect(F.body("Full Session Report") == """
        -- PROGRESS SUMMARY --
          Checked:        1
          In Progress:    1
          Not Applicable: 0
          Not Started:    1
          Bookmarked:     1
          For Export:     1
          Total Tasks:    3 (1 completed)

        --- Checked (1) ---
          Q 2.1.10 — Beta check

        --- InProgress (1) ---
          Q 1.1.1 — \("")

        --- NotApplicable (0) ---

        --- Not Started (1) ---
          Q 2.1.2 — Alpha check

        -- ALL TASKS --

        Q 2.1.2 — Alpha check
          [ ] Sight cert

        Q 2.1.10 — Beta check
          [ ] Review plan
          [x] Check log


        """)
    }

    // TV: 12 §7.10 Current Filter Results
    @Test func currentFilterResults() {
        #expect(F.body("Current Filter Results") == """
          Current Filter Results: 2 questions

        Q 2.1.10 [Inspection]
          Beta check
          Full: Is beta ok?
          Vessel: Oil, LNG | Chapter: Ch 2: Certs
          ROVIQ: Bridge, Documentation
          Status: Checked
          [x] Check log
          [ ] Review plan

        Q 1.1.1 [Data Field]
          \("")
          Full: Name of the vessel
          Vessel: All | Chapter: Ch 1: Particulars
          Status: In Progress


        """)
    }

    // TV: 12 §7.10 By Chapter
    @Test func byChapter() {
        #expect(F.body("By Chapter") == """
        --- Ch 1: Particulars (1 questions) ---
          Q 1.1.1 [InProgress] — \("")

        --- Ch 2: Certs (2 questions) ---
          Q 2.1.2 — Alpha check
          Q 2.1.10 [Checked] — Beta check


        """)
    }

    // TV: 12 §7.10 By ROVIQ Location / By Vessel Type
    @Test func byRoviqAndVessel() {
        #expect(F.body("By ROVIQ Location") == "--- Bridge (1 questions) ---\n  Q 2.1.10 — Beta check\n\n--- Documentation (1 questions) ---\n  Q 2.1.10 — Beta check\n\n--- Main Deck (1 questions) ---\n  Q 2.1.2 — Alpha check\n\n")
        #expect(F.body("By Vessel Type") == "--- Chemical (1 questions) ---\n  Q 2.1.2 — Alpha check\n\n--- LNG (1 questions) ---\n  Q 2.1.10 — Beta check\n\n--- Oil (1 questions) ---\n  Q 2.1.10 — Beta check\n\n")
    }

    // TV: 12 §7.10 Identified Tasks
    @Test func identifiedTasks() {
        #expect(F.body("Identified Tasks") == """
          Identified Tasks: 3 tasks across 2 questions
          (Pre-identified from question guidance text — no AI required)

        -- Ch 2: Certs --

          Q 2.1.2 — Alpha check
            [ ] Verify Y
            [ ] Verify Z

          Q 2.1.10 — Beta check
            [ ] Verify X


        """)
    }

    // TV: 12 §7.10 Inspection Summary
    @Test func inspectionSummary() {
        #expect(F.body("Inspection Summary") == """
          Inspection Summary: 2 questions

        --- Q 1.1.1 [InProgress] ---
          \("")
          Name of the vessel
          Vessel: All | Chapter: Ch 1: Particulars

        --- Q 2.1.10 [Checked] ---
          Beta check
          Is beta ok?
          Vessel: Oil, LNG | Chapter: Ch 2: Certs
          Objective: Obj B
          Evidence: Ev B
          Neg. Obs. Grounds: Neg B
          Tasks:
            [x] Check log
            [ ] Review plan


        """)
    }

    // TV: 12 §7.10 Pending Tasks / Questions with Tasks / Completed Tasks
    @Test func taskModes() {
        #expect(F.body("Pending Tasks") == "  Pending Tasks: 2\n\nQ 2.1.2 — Alpha check\n  [ ] Sight cert\n\nQ 2.1.10 — Beta check\n  [ ] Review plan\n\n")
        #expect(F.body("Questions with Tasks") == "  Questions with Tasks: 2\n\nQ 2.1.2 — Alpha check\n  [ ] Sight cert\n\nQ 2.1.10 — Beta check\n  [x] Check log\n  [ ] Review plan\n\n")
        #expect(F.body("Completed Tasks") == "  Completed Tasks: 1\n\nQ 2.1.10 — Beta check\n  [x] Check log\n\n")
    }

    @Test func questionLists() {
        #expect(F.body("Bookmarked Questions").hasPrefix("  Bookmarked Questions: 1 questions\n\nQ 2.1.2 [Inspection]\n  Alpha check\n  Full: Is alpha ok?\n  Vessel: Chemical | Chapter: Ch 2: Certs\n  ROVIQ: Main Deck\n  [ ] Sight cert\n"))
        #expect(F.body("For Export Tagged").hasPrefix("  Questions Tagged for Export: 1 questions\n\nQ 2.1.10 [Inspection]"))
        // Q-3: Selected Questions exports the multi-selection in natural order.
        #expect(F.body("Selected Questions", selected: ["2.1.10", "2.1.2"]).hasPrefix("  Selected Questions: 2 questions\n\nQ 2.1.2 [Inspection]"))
        #expect(F.body("Selected Questions") == "  Selected Questions: 0 questions\n\n")
        #expect(F.body("By Status").hasPrefix("--- Checked (1) ---\n  Q 2.1.10 — Beta check\n\n--- InProgress (1) ---"))
        #expect(F.body("Unknown mode") == "\n")
    }

    // TV: 12 §7.10 empty state
    @Test func emptyState() {
        let empty = SireSessionSnapshot()
        #expect(F.body("All Tasks", session: empty) == "  No tasks found.\n")
        #expect(F.body("Completed Tasks", session: empty) == "  No completed tasks found.\n")
        #expect(F.body("Pending Tasks", session: empty) == "  No pending tasks found.\n")
        #expect(F.body("Identified Tasks", identified: SireIdentifiedTasks()) == "  No identified tasks available.\n")
        let summary = F.body("Inspection Summary", session: empty)
        #expect(summary.hasPrefix("  Inspection Summary: 3 questions\n\n--- Q 1.1.1 [None] ---"))
        #expect(summary.contains("--- Q 2.1.2 [None] ---") && summary.contains("--- Q 2.1.10 [None] ---"))
    }

    // TV: 12 §7.10 file name; §4.5 bytes
    @Test func fileNameAndBytes() {
        var c = DateComponents(); c.year = 2026; c.month = 9; c.day = 30; c.hour = 14; c.minute = 32
        var cal = Calendar(identifier: .gregorian); cal.timeZone = F.zone
        let d = cal.date(from: c)!
        #expect(SireExport.defaultFileName(mode: "Print Checklist", now: d, zone: F.zone) == "SIRE_Print_Checklist_20260930_1432.txt")
        let bytes = SireExport.fileData(F.build("Print Checklist"))
        #expect(!bytes.starts(with: [0xEF, 0xBB, 0xBF]))
        #expect(!bytes.contains(0x0D))
    }

    @MainActor @Test func snapshotFromState() {
        let s = SireState()
        s.setStatus(.checked, for: "2.1.10")
        s.questionStatuses["9.9.9"] = "2"
        s.toggleBookmark("2.1.2")
        s.tasks.append(SireTask(questionNumber: "2.1.2", text: "A"))
        let snap = SireSessionSnapshot(s)
        #expect(snap.status("2.1.10") == .checked && snap.status("9.9.9") == .checked)
        #expect(snap.count(of: .checked) == 1)                       // CountByStatus compares the raw text
        #expect(snap.isBookmarked("2.1.2") && snap.hasTasks("2.1.2") && !snap.hasTasks("2.1.10"))
    }
}
