using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AA.Sire;

/// <summary>Builds text exports for every SIRE export mode (ported from the SIRE Knowledge Bank's
/// BuildExport). Pure string building over the questions + session state + identified tasks, so AA can
/// write it to a .txt file or the clipboard (and feed it to AA's own PDF/print paths).</summary>
public static class SireExport
{
    public static readonly string[] Modes =
    [
        "All Tasks", "Completed Tasks", "Pending Tasks", "Questions with Tasks",
        "Selected Questions", "For Export Tagged", "Bookmarked Questions", "Current Filter Results",
        "By Chapter", "By ROVIQ Location", "By Status", "By Vessel Type",
        "Print Checklist", "Inspection Summary", "Full Session Report", "Identified Tasks"
    ];

    public static string Build(string mode, IReadOnlyList<SireQuestion> all, SireState state,
        Dictionary<string, List<string>> identified, IReadOnlyList<SireQuestion> filtered)
    {
        var sb = new StringBuilder();
        Line(sb);
        sb.AppendLine($"  SIRE 2.0 Knowledge Bank Export — {mode}");
        sb.AppendLine($"  Generated: {DateTime.Now:yyyy-MM-dd HH:mm}");
        Line(sb);
        sb.AppendLine();

        switch (mode)
        {
            case "All Tasks": AllTasks(sb, all, state); break;
            case "Completed Tasks": TasksByCompletion(sb, all, state, true); break;
            case "Pending Tasks": TasksByCompletion(sb, all, state, false); break;
            case "Questions with Tasks": QuestionsWithTasks(sb, all, state); break;
            case "Selected Questions": QuestionList(sb, all.Where(q => q.IsSelected).OrderBy(q => q.QuestionNumber, QuestionNumberComparer.Instance).ToList(), "Selected Questions", state); break;
            case "For Export Tagged": QuestionList(sb, all.Where(q => state.IsForExport(q.QuestionNumber)).OrderBy(q => q.QuestionNumber, QuestionNumberComparer.Instance).ToList(), "Questions Tagged for Export", state); break;
            case "Bookmarked Questions": QuestionList(sb, all.Where(q => state.IsBookmarked(q.QuestionNumber)).OrderBy(q => q.QuestionNumber, QuestionNumberComparer.Instance).ToList(), "Bookmarked Questions", state); break;
            case "Current Filter Results": QuestionList(sb, filtered.ToList(), "Current Filter Results", state); break;
            case "By Chapter": ByChapter(sb, all, state); break;
            case "By ROVIQ Location": ByRoviq(sb, all); break;
            case "By Status": ByStatus(sb, all, state); break;
            case "By Vessel Type": ByVesselType(sb, all); break;
            case "Print Checklist": PrintChecklist(sb, all, state); break;
            case "Inspection Summary": InspectionSummary(sb, all, state); break;
            case "Full Session Report": FullReport(sb, all, state); break;
            case "Identified Tasks": IdentifiedTasks(sb, all, identified); break;
        }

        sb.AppendLine();
        Line(sb);
        sb.AppendLine("  Generated by AA — SIRE 2.0 Knowledge Bank");
        Line(sb);
        return sb.ToString();
    }

    private static void Line(StringBuilder sb) => sb.AppendLine(new string('=', 60));
    private static readonly IComparer<string> QC = QuestionNumberComparer.Instance;

    private static void AllTasks(StringBuilder sb, IReadOnlyList<SireQuestion> all, SireState state)
    {
        if (state.Tasks.Count == 0) { sb.AppendLine("  No tasks found."); return; }
        foreach (var g in state.Tasks.GroupBy(t => t.QuestionNumber).OrderBy(g => g.Key, QC))
        {
            var q = all.FirstOrDefault(x => x.QuestionNumber == g.Key);
            sb.AppendLine($"Q {g.Key} — {q?.ShortQuestionText ?? ""}");
            foreach (var t in g.OrderBy(t => t.CreatedAt)) sb.AppendLine($"  [{(t.IsCompleted ? "x" : " ")}] {t.Text}");
            sb.AppendLine();
        }
    }

    private static void TasksByCompletion(StringBuilder sb, IReadOnlyList<SireQuestion> all, SireState state, bool completed)
    {
        var tasks = state.Tasks.Where(t => t.IsCompleted == completed).ToList();
        if (tasks.Count == 0) { sb.AppendLine($"  No {(completed ? "completed" : "pending")} tasks found."); return; }
        sb.AppendLine($"  {(completed ? "Completed" : "Pending")} Tasks: {tasks.Count}"); sb.AppendLine();
        foreach (var g in tasks.GroupBy(t => t.QuestionNumber).OrderBy(g => g.Key, QC))
        {
            var q = all.FirstOrDefault(x => x.QuestionNumber == g.Key);
            sb.AppendLine($"Q {g.Key} — {q?.ShortQuestionText ?? ""}");
            foreach (var t in g.OrderBy(t => t.CreatedAt)) sb.AppendLine($"  [{(t.IsCompleted ? "x" : " ")}] {t.Text}");
            sb.AppendLine();
        }
    }

    private static void QuestionsWithTasks(StringBuilder sb, IReadOnlyList<SireQuestion> all, SireState state)
    {
        var nums = state.Tasks.Select(t => t.QuestionNumber).Distinct().ToHashSet();
        var qs = all.Where(q => nums.Contains(q.QuestionNumber)).OrderBy(q => q.QuestionNumber, QC).ToList();
        sb.AppendLine($"  Questions with Tasks: {qs.Count}"); sb.AppendLine();
        foreach (var q in qs)
        {
            sb.AppendLine($"Q {q.QuestionNumber} — {q.ShortQuestionText}");
            foreach (var t in state.GetTasksForQuestion(q.QuestionNumber)) sb.AppendLine($"  [{(t.IsCompleted ? "x" : " ")}] {t.Text}");
            sb.AppendLine();
        }
    }

    private static void QuestionList(StringBuilder sb, List<SireQuestion> qs, string title, SireState state)
    {
        sb.AppendLine($"  {title}: {qs.Count} questions"); sb.AppendLine();
        foreach (var q in qs)
        {
            sb.AppendLine($"Q {q.QuestionNumber} [{q.QuestionTypeDisplay}]");
            sb.AppendLine($"  {q.ShortQuestionText}");
            if (!string.IsNullOrEmpty(q.FullQuestionText)) sb.AppendLine($"  Full: {q.FullQuestionText}");
            sb.AppendLine($"  Vessel: {q.VesselTypesDisplay} | Chapter: {q.ChapterDisplay}");
            if (!string.IsNullOrEmpty(q.RoviqSequence)) sb.AppendLine($"  ROVIQ: {q.RoviqSequence}");
            var status = state.GetStatus(q.QuestionNumber);
            if (status != QuestionStatus.None) sb.AppendLine($"  Status: {q.StatusDisplay}");
            foreach (var t in state.GetTasksForQuestion(q.QuestionNumber)) sb.AppendLine($"  [{(t.IsCompleted ? "x" : " ")}] {t.Text}");
            sb.AppendLine();
        }
    }

    private static void ByChapter(StringBuilder sb, IReadOnlyList<SireQuestion> all, SireState state)
    {
        foreach (var g in all.GroupBy(q => q.ChapterDisplay).OrderBy(g => int.TryParse(g.First().Chapter, out var n) ? n : 999))
        {
            sb.AppendLine($"--- {g.Key} ({g.Count()} questions) ---");
            foreach (var q in g.OrderBy(q => q.QuestionNumber, QC))
            {
                var status = state.GetStatus(q.QuestionNumber);
                var tag = status != QuestionStatus.None ? $" [{status}]" : "";
                sb.AppendLine($"  Q {q.QuestionNumber}{tag} — {q.ShortQuestionText}");
            }
            sb.AppendLine();
        }
    }

    private static void ByRoviq(StringBuilder sb, IReadOnlyList<SireQuestion> all)
    {
        var map = new Dictionary<string, List<SireQuestion>>(StringComparer.OrdinalIgnoreCase);
        foreach (var q in all)
            foreach (var loc in q.RoviqLocations)
                (map.TryGetValue(loc, out var l) ? l : map[loc] = new()).Add(q);
        foreach (var kv in map.OrderBy(k => k.Key))
        {
            sb.AppendLine($"--- {kv.Key} ({kv.Value.Count} questions) ---");
            foreach (var q in kv.Value.OrderBy(q => q.QuestionNumber, QC)) sb.AppendLine($"  Q {q.QuestionNumber} — {q.ShortQuestionText}");
            sb.AppendLine();
        }
    }

    private static void ByStatus(StringBuilder sb, IReadOnlyList<SireQuestion> all, SireState state)
    {
        foreach (var status in new[] { QuestionStatus.Checked, QuestionStatus.InProgress, QuestionStatus.NotApplicable, QuestionStatus.None })
        {
            var qs = all.Where(q => state.GetStatus(q.QuestionNumber) == status).OrderBy(q => q.QuestionNumber, QC).ToList();
            var label = status == QuestionStatus.None ? "Not Started" : status.ToString();
            sb.AppendLine($"--- {label} ({qs.Count}) ---");
            foreach (var q in qs) sb.AppendLine($"  Q {q.QuestionNumber} — {q.ShortQuestionText}");
            sb.AppendLine();
        }
    }

    private static void ByVesselType(StringBuilder sb, IReadOnlyList<SireQuestion> all)
    {
        var map = new Dictionary<string, List<SireQuestion>>(StringComparer.OrdinalIgnoreCase);
        foreach (var q in all)
            foreach (var vt in q.VesselTypes)
                (map.TryGetValue(vt, out var l) ? l : map[vt] = new()).Add(q);
        foreach (var kv in map.OrderBy(k => k.Key))
        {
            sb.AppendLine($"--- {kv.Key} ({kv.Value.Count} questions) ---");
            foreach (var q in kv.Value.OrderBy(q => q.QuestionNumber, QC)) sb.AppendLine($"  Q {q.QuestionNumber} — {q.ShortQuestionText}");
            sb.AppendLine();
        }
    }

    private static void PrintChecklist(StringBuilder sb, IReadOnlyList<SireQuestion> all, SireState state)
    {
        sb.AppendLine("  INSPECTION CHECKLIST");
        sb.AppendLine($"  Total questions: {all.Count}"); sb.AppendLine();
        foreach (var q in all.OrderBy(q => q.QuestionNumber, QC))
        {
            var mark = state.GetStatus(q.QuestionNumber) switch
            { QuestionStatus.Checked => "[x]", QuestionStatus.InProgress => "[~]", QuestionStatus.NotApplicable => "[N/A]", _ => "[ ]" };
            sb.AppendLine($"{mark} Q {q.QuestionNumber} — {q.ShortQuestionText}");
            foreach (var t in state.GetTasksForQuestion(q.QuestionNumber)) sb.AppendLine($"      [{(t.IsCompleted ? "x" : " ")}] {t.Text}");
        }
    }

    private static void InspectionSummary(StringBuilder sb, IReadOnlyList<SireQuestion> all, SireState state)
    {
        var qs = state.QuestionStatuses.Count > 0
            ? all.Where(q => state.GetStatus(q.QuestionNumber) != QuestionStatus.None).OrderBy(q => q.QuestionNumber, QC).ToList()
            : all.OrderBy(q => q.QuestionNumber, QC).ToList();
        sb.AppendLine($"  Inspection Summary: {qs.Count} questions"); sb.AppendLine();
        foreach (var q in qs)
        {
            sb.AppendLine($"--- Q {q.QuestionNumber} [{state.GetStatus(q.QuestionNumber)}] ---");
            sb.AppendLine($"  {q.ShortQuestionText}");
            if (!string.IsNullOrEmpty(q.FullQuestionText)) sb.AppendLine($"  {q.FullQuestionText}");
            sb.AppendLine($"  Vessel: {q.VesselTypesDisplay} | Chapter: {q.ChapterDisplay}");
            if (!string.IsNullOrEmpty(q.Objective)) sb.AppendLine($"  Objective: {q.Objective}");
            if (!string.IsNullOrEmpty(q.ExpectedEvidence)) sb.AppendLine($"  Evidence: {q.ExpectedEvidence}");
            if (!string.IsNullOrEmpty(q.PotentialNegativeObservationGrounds)) sb.AppendLine($"  Neg. Obs. Grounds: {q.PotentialNegativeObservationGrounds}");
            var tasks = state.GetTasksForQuestion(q.QuestionNumber);
            if (tasks.Count > 0) { sb.AppendLine("  Tasks:"); foreach (var t in tasks) sb.AppendLine($"    [{(t.IsCompleted ? "x" : " ")}] {t.Text}"); }
            sb.AppendLine();
        }
    }

    private static void FullReport(StringBuilder sb, IReadOnlyList<SireQuestion> all, SireState state)
    {
        sb.AppendLine("-- PROGRESS SUMMARY --");
        sb.AppendLine($"  Checked:        {state.CountByStatus(QuestionStatus.Checked)}");
        sb.AppendLine($"  In Progress:    {state.CountByStatus(QuestionStatus.InProgress)}");
        sb.AppendLine($"  Not Applicable: {state.CountByStatus(QuestionStatus.NotApplicable)}");
        sb.AppendLine($"  Not Started:    {all.Count - state.QuestionStatuses.Count}");
        sb.AppendLine($"  Bookmarked:     {state.Bookmarks.Count}");
        sb.AppendLine($"  For Export:     {state.ForExport.Count}");
        sb.AppendLine($"  Total Tasks:    {state.TotalTaskCount} ({state.CompletedTaskCount} completed)");
        sb.AppendLine();
        ByStatus(sb, all, state);
        sb.AppendLine("-- ALL TASKS --"); sb.AppendLine();
        AllTasks(sb, all, state);
    }

    private static void IdentifiedTasks(StringBuilder sb, IReadOnlyList<SireQuestion> all, Dictionary<string, List<string>> identified)
    {
        if (identified.Count == 0) { sb.AppendLine("  No identified tasks available."); return; }
        var total = identified.Values.Sum(v => v.Count);
        sb.AppendLine($"  Identified Tasks: {total} tasks across {identified.Count} questions");
        sb.AppendLine("  (Pre-identified from question guidance text — no AI required)"); sb.AppendLine();
        var grouped = identified
            .Select(kv => new { kv.Key, Tasks = kv.Value, Q = all.FirstOrDefault(q => q.QuestionNumber == kv.Key) })
            .Where(x => x.Q != null)
            .GroupBy(x => x.Q!.ChapterDisplay)
            .OrderBy(g => int.TryParse(g.First().Q!.Chapter, out var n) ? n : 999);
        foreach (var chapter in grouped)
        {
            sb.AppendLine($"-- {chapter.Key} --"); sb.AppendLine();
            foreach (var item in chapter.OrderBy(x => x.Key, QC))
            {
                sb.AppendLine($"  Q {item.Key} — {item.Q!.ShortQuestionText}");
                foreach (var task in item.Tasks) sb.AppendLine($"    [ ] {task}");
                sb.AppendLine();
            }
        }
    }
}
